### ISSUE TITLE
Build fails on Sonoma 14.8.2

### ISSUE THREAD

**Issue by m4rkky** [stass/blew#3]
I have upgraded my Xcode from 15.4 to 16.2 and get the same error whether building from source or using brew.

[24/27] Compiling MCP OAuthAuthorizationCodeFlow.swift
/private/tmp/blew-20260427-84084-cr1orj/blew-0.2.2/.build/checkouts/swift-sdk/Sources/MCP/Base/Transports/HTTPClientTransport.swift:485:31: error: missing argument for parameter 'of' in call

I'm new to swift, so whilst I can see that the function is expecting a parameter, I don't know how to fix.

blew looks like an extremely useful utility that I would definitely like to use.

**Comment by stass** [comment]
Thanks for letting me know -- let me update mine and fix.

**Comment by m4rkky** [comment]
Thanks, I look forward to trying out the tool.

**Comment by stass** [comment]
Hi @m4rkky -- it looks like the official MCP SDK we are using depends on Swift 6.1 primitives -- and Swift 6.1 is only included with XCode 16.3.  I wonder if you can try the newer XCode version to see if that resolves this issue for you?  Thanks!

**Comment by m4rkky** [comment]
I'm pretty sure Xcode 16.2 was the last version to support Sonoma.  I'll check again, I don't particularly want to move to a more recent version of macOS...

**Comment by stass** [comment]
You might be right.  The other option I guess would be to conditionally disable MCP server functionality for builds with Swift < 6.1.  I'll see if I can do that easily.

Unfortunately MCP SDK moved to Swift 6.1 and I'm not sure it'd be a good approach to apply local patches to it. :(

**Comment by m4rkky** [comment]
Disabling MCP server would be fine for my use, and appreciated if you are able to.  Thanks.

**Comment by stass** [comment]
I just pushed a change to make MCP conditional -- can you try building?  Thanks!

**Comment by m4rkky** [comment]
Compiles successfully and executable works as described from the quick look that I've had just now.  Thanks!
